//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 06:13:38 PM AST 
//


package com.ats.application.network.webclient.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.app.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.app.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebClientXSDDTO }
     * 
     */
    public WebClientXSDDTO createWebClient() {
        return new WebClientXSDDTO();
    }

    /**
     * Create an instance of {@link WebClientXSDDTO.AppURLs }
     * 
     */
    public WebClientXSDDTO.AppURLs createWebClientAppURLs() {
        return new WebClientXSDDTO.AppURLs();
    }

    /**
     * Create an instance of {@link WebClientXSDDTO.ProxyConfig }
     * 
     */
    public WebClientXSDDTO.ProxyConfig createWebClientProxyConfig() {
        return new WebClientXSDDTO.ProxyConfig();
    }

    /**
     * Create an instance of {@link WebClientXSDDTO.FileConfig }
     * 
     */
    public WebClientXSDDTO.FileConfig createWebClientFileConfig() {
        return new WebClientXSDDTO.FileConfig();
    }

    /**
     * Create an instance of {@link WebClientXSDDTO.SSLProtocol }
     * 
     */
    public WebClientXSDDTO.SSLProtocol createWebClientSSLProtocol() {
        return new WebClientXSDDTO.SSLProtocol();
    }

}
