//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 06:13:38 PM AST 
//


package com.ats.application.network.webclient.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RunMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AppURLs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProxyConfig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Server" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UserPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FileConfig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CertificatePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CertificatePassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InputFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OutputFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SSLProtocol">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runMode",
    "appURLs",
    "proxyConfig",
    "fileConfig",
    "sslProtocol"
})
@XmlRootElement(name = "WebClient")
public class WebClientXSDDTO {

    @XmlElement(name = "RunMode", required = true)
    protected String runMode;
    @XmlElement(name = "AppURLs", required = true)
    protected WebClientXSDDTO.AppURLs appURLs;
    @XmlElement(name = "ProxyConfig", required = true)
    protected WebClientXSDDTO.ProxyConfig proxyConfig;
    @XmlElement(name = "FileConfig", required = true)
    protected WebClientXSDDTO.FileConfig fileConfig;
    @XmlElement(name = "SSLProtocol", required = true)
    protected WebClientXSDDTO.SSLProtocol sslProtocol;

    /**
     * Gets the value of the runMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunMode() {
        return runMode;
    }

    /**
     * Sets the value of the runMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunMode(String value) {
        this.runMode = value;
    }

    /**
     * Gets the value of the appURLs property.
     * 
     * @return
     *     possible object is
     *     {@link WebClientXSDDTO.AppURLs }
     *     
     */
    public WebClientXSDDTO.AppURLs getAppURLs() {
        return appURLs;
    }

    /**
     * Sets the value of the appURLs property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebClientXSDDTO.AppURLs }
     *     
     */
    public void setAppURLs(WebClientXSDDTO.AppURLs value) {
        this.appURLs = value;
    }

    /**
     * Gets the value of the proxyConfig property.
     * 
     * @return
     *     possible object is
     *     {@link WebClientXSDDTO.ProxyConfig }
     *     
     */
    public WebClientXSDDTO.ProxyConfig getProxyConfig() {
        return proxyConfig;
    }

    /**
     * Sets the value of the proxyConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebClientXSDDTO.ProxyConfig }
     *     
     */
    public void setProxyConfig(WebClientXSDDTO.ProxyConfig value) {
        this.proxyConfig = value;
    }

    /**
     * Gets the value of the fileConfig property.
     * 
     * @return
     *     possible object is
     *     {@link WebClientXSDDTO.FileConfig }
     *     
     */
    public WebClientXSDDTO.FileConfig getFileConfig() {
        return fileConfig;
    }

    /**
     * Sets the value of the fileConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebClientXSDDTO.FileConfig }
     *     
     */
    public void setFileConfig(WebClientXSDDTO.FileConfig value) {
        this.fileConfig = value;
    }

    /**
     * Gets the value of the sslProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link WebClientXSDDTO.SSLProtocol }
     *     
     */
    public WebClientXSDDTO.SSLProtocol getSSLProtocol() {
        return sslProtocol;
    }

    /**
     * Sets the value of the sslProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebClientXSDDTO.SSLProtocol }
     *     
     */
    public void setSSLProtocol(WebClientXSDDTO.SSLProtocol value) {
        this.sslProtocol = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "url"
    })
    public static class AppURLs {

        @XmlElement(name = "URL")
        protected List<String> url;

        /**
         * Gets the value of the url property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the url property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getURL().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getURL() {
            if (url == null) {
                url = new ArrayList<String>();
            }
            return this.url;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CertificatePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CertificatePassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InputFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OutputFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "certificatePath",
        "certificatePassword",
        "inputFilePath",
        "outputFilePath"
    })
    public static class FileConfig {

        @XmlElement(name = "CertificatePath", required = true)
        protected String certificatePath;
        @XmlElement(name = "CertificatePassword", required = true)
        protected String certificatePassword;
        @XmlElement(name = "InputFilePath", required = true)
        protected String inputFilePath;
        @XmlElement(name = "OutputFilePath", required = true)
        protected String outputFilePath;

        /**
         * Gets the value of the certificatePath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificatePath() {
            return certificatePath;
        }

        /**
         * Sets the value of the certificatePath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificatePath(String value) {
            this.certificatePath = value;
        }

        /**
         * Gets the value of the certificatePassword property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificatePassword() {
            return certificatePassword;
        }

        /**
         * Sets the value of the certificatePassword property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificatePassword(String value) {
            this.certificatePassword = value;
        }

        /**
         * Gets the value of the inputFilePath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInputFilePath() {
            return inputFilePath;
        }

        /**
         * Sets the value of the inputFilePath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInputFilePath(String value) {
            this.inputFilePath = value;
        }

        /**
         * Gets the value of the outputFilePath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputFilePath() {
            return outputFilePath;
        }

        /**
         * Sets the value of the outputFilePath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputFilePath(String value) {
            this.outputFilePath = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Server" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UserPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "server",
        "port",
        "userName",
        "userPassword"
    })
    public static class ProxyConfig {

        @XmlElement(name = "Server", required = true)
        protected String server;
        @XmlElement(name = "Port", required = true)
        protected String port;
        @XmlElement(name = "UserName", required = true)
        protected String userName;
        @XmlElement(name = "UserPassword", required = true)
        protected String userPassword;

        /**
         * Gets the value of the server property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServer() {
            return server;
        }

        /**
         * Sets the value of the server property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServer(String value) {
            this.server = value;
        }

        /**
         * Gets the value of the port property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPort() {
            return port;
        }

        /**
         * Sets the value of the port property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPort(String value) {
            this.port = value;
        }

        /**
         * Gets the value of the userName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserName() {
            return userName;
        }

        /**
         * Sets the value of the userName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserName(String value) {
            this.userName = value;
        }

        /**
         * Gets the value of the userPassword property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserPassword() {
            return userPassword;
        }

        /**
         * Sets the value of the userPassword property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserPassword(String value) {
            this.userPassword = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version"
    })
    public static class SSLProtocol {

        @XmlElement(name = "Version")
        protected List<String> version;

        /**
         * Gets the value of the version property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the version property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getVersion() {
            if (version == null) {
                version = new ArrayList<String>();
            }
            return this.version;
        }

    }

}
